version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo installing npm dependencies...
      - rm -rf node_modules package-lock.json
      - npm install
  
  build:
    commands:
      - echo building app..
      - npm run build
    
  post_build:
    command:
      - echo deploying to s3...
      - aws s3 sync dist/ s3://manohari-portfolio --delete
      - echo invalidating cloudfront...
      - aws cloudfront create-invalidation --distribution-id ERXE95GJLM32J --path "/*"
  
artifacts:
  files:
    - '**/*'
