version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo installing npm dependencies...
      - rm -rf node_modules package-lock.json
      - npm install
  
  build:
    commands:
      - echo building app..
      - npm run build
    
  post_build:
    commands:
      - echo invalidating cloudfront...
      - aws cloudfront create-invalidation --distribution-id ERXE95GJLM32J --paths "/*"
  
artifacts:
  base-directory: dist
  files:
    - '**/*'
